DATABASE_URL = "sqlite://"  # in-memory SQLite

MAX_CREDITS_PER_SEMESTER = 18

# Seed data sizes
NUM_DEPARTMENTS = 12
PROFESSORS_PER_DEPARTMENT = 10
COURSES_PER_PROFESSOR = 5
STUDENTS_PER_DEPARTMENT = 1000

# Pagination defaults
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
